### PR TITLE
Fixed display, and changed the <a> format for link results.

### PR DESCRIPTION
**Pull request by taylorperkins**
Cards are now set in nice lil rows. I set the images to a fixed height, and also changed the url format so there was no overhang. Looks pretty neat and clean!

### CODE REVIEW

**Comment by rueTH** [comment]
....is someone bored in backend, @taylorperkins ?

**Comment by helanan** [comment]
changes look good! bitmoji

**Comment by taylorperkins** [comment]
hahaha PERHAPS.

**Comment by rueTH** [comment]
MUST BE NICE, perkins. *eyeroll*

*coughSHOWOFFcough*

**Comment by taylorperkins** [comment]
lolol

**Pull request merged**
